name: Docker Image CI

on:
  push:
    branches: [ "develop-main" ]
  pull_request:
    branches: [ "develop-main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker network create rest-net && docker-compose up --build && exit 0
